---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-manager
  namespace: default
rules:
- apiGroups: ["", "batch", "extensions", "apps", "policy"]
  resources: ["*"]
  verbs: ["*"]

